version: "3"
services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  web:
    build: .
    # command: ./docker-entrypoint.sh
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /tmp/app/mysqld:/run/mysqld
    depends_on:
      - postgres
  migration:
    build: .
    command: python manage.py migrate --noinput
    volumes:
      - .:/app
    depends_on:
      - postgres
  redis:
    image: redis:alpine


networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    pgadmin: