# Generated by Django 4.1.3 on 2022-11-10 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('0', 'Simple Employee'), ('1', 'Hr Manager'), ('2', 'Payroll Manager')], default='0', max_length=1),
        ),
    ]
