# Generated by Django 4.1.3 on 2022-11-09 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='name',
            field=models.CharField(default='hossein', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hrmanager',
            name='name',
            field=models.CharField(default='ali', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payrollmanager',
            name='name',
            field=models.CharField(default='nastaran', max_length=255),
            preserve_default=False,
        ),
    ]
