# Generated by Django 4.1.3 on 2022-11-10 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_alter_role_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='title',
            field=models.CharField(choices=[('simple_employee', 'Simple Employee'), ('hr_manager', 'Hr Manager'), ('payroll_manager', 'Pay Roll Manager')], max_length=64),
        ),
    ]
