# Generated by Django 4.1.3 on 2022-11-10 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_employeeprofile_role_delete_baseemployee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='national_id',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='title',
            field=models.CharField(choices=[('0', 'Simple Employee'), ('1', 'Hr Manager'), ('2', 'Payroll Manager')], max_length=1),
        ),
    ]
