# Generated by Django 4.1.3 on 2022-11-09 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_employee_name_hrmanager_name_payrollmanager_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseemployee',
            name='salary',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Salary',
        ),
    ]
